export default [
  {
    key: "world_icons",
    title: "World Icons",
    description: "Interesting facts about famous buildings in the world and modern architectural wonders.",
    image: require('./TulsherWiulaLarenInamgesWopei/woldrionc.png'), // replace with your actual image path
    facts: [
      "The tallest building in the world reaches over 800 meters.",
      "The ancient pyramids were built without modern technology.",
      "Some historical buildings have survived earthquakes and wars.",
      "The Eiffel Tower can grow taller in the heat due to the expansion of metal.",
      "The Colosseum could accommodate over 50,000 spectators.",
      "Some bridges are designed to bend in the wind.",
      "Skyscrapers have special anti-vibration systems.",
      "Some ancient temples were built over thousands of years.",
      "There are buildings in the world in the shape of ships, flowers, and even animals.",
      "The stone in ancient buildings was often worked by hand.",
      "The most famous buildings often become symbols of cities.",
      "Some historical buildings are tilted, but still stand.",
      "Modern skyscrapers use glass that reflects the sun.",
      "In many countries, architecture reflects the culture of the people.",
      "The oldest structures in the world are over 4,000 years old.",
      "Some buildings are specially illuminated at night for effect.",
      "Bridges can stretch for tens of kilometers.",
      "Some palaces have hundreds of rooms.",
      "Architectural marvels often took decades to build.",
      "Large structures require constant maintenance even after hundreds of years.",
    ],
  },
  {
    key: "build_secrets",
    title: "Build Secrets",
    description: "Facts about building materials, structures, technologies and engineering solutions.",
    image: require('./TulsherWiulaLarenInamgesWopei/bisectils.png'), // replace with your actual image path
    facts: [
      "The foundation is the most important part of a building.",
      "Concrete becomes stronger over time.",
      "There are often steel rods inside concrete columns.",
      "Roofs have different shapes to protect against rain and snow.",
      "The glass in modern buildings can be extremely strong.",
      "Skyscrapers have deep underground supports.",
      "Steel beams help the buildings support their weight.",
      "Buildings are designed to withstand wind forces.",
      "Elevators work thanks to a system of counterweights.",
      "Electrical and water systems are often hidden in the walls.",
      "Architects first create drawings and 3D models.",
      "Building materials are tested for strength.",
      "Insulation helps retain heat in the winter.",
      "Windows can reduce noise from the street.",
      "Buildings are designed with fire safety in mind.",
      "Cranes can lift loads weighing hundreds of tons.",
      "Stairs have safety standards for height and width.",
      "Some buildings have moving parts of the facade.",
      "Modern materials can be lightweight, but very strong.",
      "Construction begins with a thorough analysis of the soil.",
    ],
  },
  {
    key: "smart_cities",
    title: "Smart Cities",
    description: "Facts about how cities grow, how areas are planned, and how urban infrastructure works.",
    image: require('./TulsherWiulaLarenInamgesWopei/sitimarts.png'), // replace with your actual image path
    facts: [
      "Smart cities use sensors to collect data.",
      "Traffic lights can automatically change mode depending on traffic.",
      "Electric buses reduce air pollution.",
      "Solar panels convert the sun into electricity.",
      "Green roofs help cool buildings.",
      "Some cities have dedicated bike lanes.",
      "Smart lights can be turned on only when needed.",
      "GPS systems help plan routes.",
      "Rainwater can be collected and reused.",
      "City parks improve air quality.",
      "Cameras help monitor road safety.",
      "Some buildings automatically adjust the temperature inside.",
      "Underground parking saves urban space.",
      "Transportation apps show real-time traffic.",
      "Energy-efficient buildings use fewer resources.",
      "Smart meters help save water and electricity.",
      "Waste sorting reduces environmental damage.",
      "Some cities are using driverless vehicles.",
      "City planning affects the comfort of residents.",
      "Future cities are becoming increasingly green and technological.",
    ],
  },
];